MESSAGES = {
    # item
    "item_not_found": "آیتم داده شده" + " '{item}' " + "پیدا نشد!",
    "item_deleted_previously": "آیتم داده شده" + " '{item}' " + "قبلا پاک شده است!",
    "duplicate_item": "آیتم داده شده" + " '{item}' " + "تکراری است!",
    "unregistered_item": "آیتم داده شده" + " '{item}' " + "قبلا ثبت نشده است!",
    "invalid_value": "مقدار داده شده" + " '{value}' " + "درست (معتبر) نیست!",
    "invalid_value_with_reason": "مقدار داده شده" + " '{value}' " + "درست (معتبر) نیست چون" + " {reason} ",
    "frozen_item": "آیتم داده شده" + " '{item}' " + "فریز شده است و نمیتواند پاک شود!",
    "not_given_data": "داده" + " '{data}' " + "باید داده شود!",

    # User Authorization/Authentication
    "not_admin_user": "شما ادمین نیستید و نمیتوانید به این آدرس" + " '{route}' " + "دسترسی داشته باشید!",
    "admin_user": "شما ادمین هستید و نمیتوانید به این آدرس" + " '{route}' " + "دسترسی داشته باشید!",
    "invalid_token": "توکن داده شده درست (معتبر) نیست!",
    "expired_token": "توکن داده شده منقضی شده است!",
    "invalid_password": "پسورد داده شده معتبر نیست!",
    "not_allowed": "این اقدام اجازه داده نشده است.",
    "unauthorized_user": "کاربر شناسایی نشده است!",
    "user_suspension": "کاربر معلق شده است!",

    # Service Authorization/Authentication
    "realm_not_found": "حوزه" + " '{realm}' " + "پیدا نشد!",
    "unauthorized_service": "سرویس شناسایی نشد!",

    # OTP
    "send_otp": "کد پیامکی ارسال شده است!",
    "invalid_otp": "کد وارد شده صحیح نیست. لطفا دوباره تلاش کنید!",
    "time_limit_otp": "کد پیامکی به تازگی ارسال شده است. لطفا" + " '{duration}' " + "بعد تلاش کنید.",

    # Server
    "server_error": "خطای غیر منتظره رخ داده است!!! چند دقیقه بعد دوباره تلاش کنید."
                    " این خطا به صورت خودکار به ادمین اطلاع داده شده است!",
    "internal_server_error": "خطای غیر منتظره رخ داده است!!! چند دقیقه بعد دوباره تلاش کنید."
                             " این خطا به صورت خودکار به ادمین اطلاع داده شده است!",
    "service_unavailable": "سرویس مورد نظر" + " '{service}' "
                           + "موقتا در دسترسی نیست! این مورد به صورت خودکار به ادمین اطلاع داده شده است.",

    # Common
    "success_message": "عملیات موفقیت آمیز بود.",
    "failure_message": "عملیات ناموفق بود!",

    # Validation errors
    'field required': "این فیلد الزامی میباشد.",
    'extra fields not permitted': "دادن فیلد اضافی ممنوع است.",
    'none is not an allowed value': "مقدار" + " null " + "مورد قبول نیست.",
    'value is not none': "مقدار" + " null " + "نیست.",
    'value could not be parsed to a boolean': "مقدار داده شده قابل تبدیل به بولین نیست!",
    'byte type expected': "نوع بایت باید داده شود!",
    'value is not a valid dict': "آبجکت قابل قبول نیست!",
    'value is not a valid email address': "ایمیل معتبر نیست!",
    'invalid or missing URL scheme': "آدرس معتبر نیست!",
    'URL scheme not permitted': "آدرس معتبر نیست!",
    'userinfo required in URL but missing': "اطلاعات کاربر در آدرس مورد نیاز است اما فریتاده نشده است!",
    'URL host invalid': "آدرس هاست نامعتبر است!",
    'URL host invalid, top level domain required': "آدرس هاست نامعتبر است، دامین مورد نیاز است.",
    'URL port invalid, port cannot exceed 65535': "ءورت نامعتبر است، پورت باید کمتر از ۶۵۵۳۵ باشد.",
    'value is not a valid integer': "مقدار عدد صحیح نیست.",
    'value is not a valid float': "مقدار عدد اعشاری نیست.",
    'value is not a valid path': "مقدار آدرس فایل یا فولدر نیست.",
    'value is not a valid sequence': "مقدار توالی از داده ها نیست.",
    'value is not a valid iterable': "مقدار قابل شمارش نیست.",
    'value is not a valid list': "مقدار داده شده لیست نیست.",
    'value is not a valid set': "مقدار داده شده مجموعه نیست.",
    'value is not a valid frozenset': "مقدار داده شده مجموعه فریزشده نیست.",
    'value is not a valid deque': "مقدار داده شده صف دو طرفه نیست.",
    'value is not a valid tuple': "مقدار داده شده تاپل نیست.",
    'the list has duplicated items': "لیست داده شده دارای مقدار تکراری است.",
    'str type expected': "رشته متنی مورد نظر است.",
    'ensure this value is a finite number': "مطمپن شوید که یک مقدار متناهی وارد میکنید.",
    'value is not a valid decimal': "مقدار داده شده دسیمال نیست.",
    'invalid datetime format': "فرمت تاریخ و زمان معتبر نیست.",
    'invalid date format': "فرمت تاریخ معتبر نیست.",
    'date is not in the past': "تاریخ باید مربوط به گذشته باشد.",
    'date is not in the future': "تاریخ در مورد آینده نیست.",
    'invalid time format': "زمان داده شده معتبر نیست.",
    'invalid duration format': "بازه زمانی داده شده معتبر نیست.",
    'value is not a valid hashable': "مقدار داده شده قابل هش نیست.",
    'value is not a valid uuid': "مقدار داده شده uuid معتبر نیست",
    'a class is expected': "کلاس مورد انظار است.",
    'Invalid JSON': "JSON معتبر نیست.",
    'JSON object must be str, bytes or bytearray': "JSON باید متن، بایت و یا آرایه ای از بایت ها باشد.",
    'Invalid regular expression': "عبارات با قاعده (regex) معتبر نیست.",
    'value is not a valid IPv4 or IPv6 address': "مقدار داده شده IPv4 یا IPv6 معتبر نیست.",
    'value is not a valid IPv4 or IPv6 interface': "مقدار داده شده IPv4 یا IPv6 معتبر نیست.",
    'value is not a valid IPv4 or IPv6 network': "مقدار داده شده IPv4 یا IPv6 معتبر نیست.",
    'value is not a valid IPv4 address': "مقدار داده شده IPv4 معتبر نیست.",
    'value is not a valid IPv6 address': "مقدار داده شده IPv6 معتبر نیست.",
    'value is not a valid IPv4 network': "مقدار داده شده IPv4 معتبر نیست.",
    'value is not a valid IPv6 network': "مقدار داده شده IPv6 معتبر نیست.",
    'value is not a valid IPv4 interface': "مقدار داده شده IPv4 معتبر نیست.",
    'value is not a valid IPv6 interface': "مقدار داده شده IPv6 معتبر نیست.",
    'value is not a valid boolean': "مقدار داده شده بولین معتبر نیست.",
    'card number is not all digits': "شماره کارت باید تماما عدد باشد.",
    'card number is not luhn valid': "شماره کارت معتبر نیست.",
    'could not parse value and unit from byte string': "بایت داده شده قابل تفسیر کردن نیست.",
}
